"""
Domain schemas and typed structures for VyaparMitra Phase 5 Hindi AI Business Copilot.
"""

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field


class Language(str, Enum):
    HINDI = "hi"
    HINGLISH = "hinglish"
    ENGLISH = "en"

    @classmethod
    def _missing_(cls, value):
        if isinstance(value, str):
            val_lower = value.lower().strip()
            if val_lower in ("hindi", "hi", "devanagari"):
                return cls.HINDI
            elif val_lower in ("english", "en"):
                return cls.ENGLISH
            elif val_lower in ("hinglish", "hi-en", "roman"):
                return cls.HINGLISH
        return super()._missing_(value)



class Intent(str, Enum):
    SALES_SUMMARY = "SALES_SUMMARY"
    SALES_TREND = "SALES_TREND"
    SALES_FORECAST = "SALES_FORECAST"
    PRODUCT_PERFORMANCE = "PRODUCT_PERFORMANCE"
    PRODUCT_DEMAND_FORECAST = "PRODUCT_DEMAND_FORECAST"
    INVENTORY_RECOMMENDATION = "INVENTORY_RECOMMENDATION"
    CUSTOMER_ANALYSIS = "CUSTOMER_ANALYSIS"
    CUSTOMER_RISK = "CUSTOMER_RISK"
    RETENTION_RECOMMENDATION = "RETENTION_RECOMMENDATION"
    CROSS_SELL = "CROSS_SELL"
    PRICING_RECOMMENDATION = "PRICING_RECOMMENDATION"
    BUSINESS_TREND = "BUSINESS_TREND"
    ANOMALY = "ANOMALY"
    DAILY_ACTION_PLAN = "DAILY_ACTION_PLAN"
    PAYMENT_ANALYSIS = "PAYMENT_ANALYSIS"
    CATEGORY_ANALYSIS = "CATEGORY_ANALYSIS"
    TIME_ANALYSIS = "TIME_ANALYSIS"
    RECOMMENDATION_EXPLANATION = "RECOMMENDATION_EXPLANATION"
    GENERAL_BUSINESS_SUMMARY = "GENERAL_BUSINESS_SUMMARY"
    EXECUTIVE_BRIEF = "EXECUTIVE_BRIEF"
    GREETING = "GREETING"
    HELP_CAPABILITIES = "HELP_CAPABILITIES"
    GLOSSARY_EXPLANATION = "GLOSSARY_EXPLANATION"
    BENCHMARK = "BENCHMARK"
    OUT_OF_DOMAIN = "OUT_OF_DOMAIN"
    UNKNOWN = "UNKNOWN"


class QueryPlan(BaseModel):
    """Execution plan generated by QueryRouter for targeted retrieval."""
    intent: Intent
    entities: Dict[str, Any] = Field(default_factory=dict)
    time_range: Optional[str] = None
    merchant_id: Optional[str] = None
    product_id: Optional[str] = None
    customer_id: Optional[str] = None
    category: Optional[str] = None
    recommendation_id: Optional[str] = None
    required_sources: List[str] = Field(default_factory=list)
    response_language: Language = Language.HINGLISH
    needs_knowledge: bool = False



class Fact(BaseModel):
    """Verified individual data point retrieved from Phase 1-4 data marts."""
    key: str
    value: Any
    source: str
    category: str = "historical"  # 'historical', 'prediction', 'recommendation', 'knowledge'


class SourceReference(BaseModel):
    """Explicit citation tracking the exact artifact behind each claim."""
    source: str
    artifact: str
    entity: Optional[str] = None
    description: Optional[str] = None


class BusinessContext(BaseModel):
    """Consolidated, structured business payload passed into prompt generator and LLM."""
    intent: str
    query: str
    language: str
    facts: List[Fact] = Field(default_factory=list)
    metrics: Dict[str, Any] = Field(default_factory=dict)
    recommendations: List[Dict[str, Any]] = Field(default_factory=list)
    evidence: List[Dict[str, Any]] = Field(default_factory=list)
    source_references: List[SourceReference] = Field(default_factory=list)
    limitations: List[str] = Field(default_factory=list)
    knowledge_snippets: List[str] = Field(default_factory=list)


class ValidationResult(BaseModel):
    """Post-generation grounding and hallucination guard check result."""
    valid: bool = True
    unsupported_claims: List[str] = Field(default_factory=list)
    numeric_mismatches: List[str] = Field(default_factory=list)
    entity_mismatches: List[str] = Field(default_factory=list)
    details: Optional[str] = None


class CopilotResponse(BaseModel):
    """Final, grounded copilot response delivered to merchant or API client."""
    answer: str
    intent: str
    language: str
    sources: List[SourceReference] = Field(default_factory=list)
    evidence: List[Dict[str, Any]] = Field(default_factory=list)
    recommendations: List[Dict[str, Any]] = Field(default_factory=list)
    confidence: Optional[float] = None
    validation: ValidationResult
    generated_at: str
